
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: ninja_training_development

test:
  <<: *default
  database: ninja_training_test

production:
  <<: *default
  database: ninja_training_production
  username:
  password:
