# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05ae5961c73300678c4eb394736e3e8286c0871f938aa3eb3647186e7db5b13a748f6ea7c7b788ed83fdbd23c479e42abd5b47d6916dafd5cb32b100b6c3ed6b

test:
  secret_key_base: 8617322dd8527dee23850dd9d5d8b4a9bf41430de9b20a2580dca17aef04f4b2a30124ac7401e521891992e23d7298a5534485927440988cc8f7ed0c1ff5690b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
